(function($) {
	var SpriteArchive = {
		class2Key: {
			selectionShape: "selectionShape",
			Application: "application",
			Azienda: "company",
			BusinessProcess: "process",
			BusinessServices: "process",
			BusinessService: "process",
			DepMgt: "process",
			Desktop: "terminal",
			Dipendente: "employee",
			ExternalEmployee: "employee",
			GestioneModifiche: "process",
			ImacTrans: "process",
			InternalEmployee: "employee",
			Mobile: "mobile",
			NetworkBox: "networkbox",
			NetworkInterface: "networkinterface",
			NetworkDevice: "networkinterface",
			OperationalAreas: "operationalareas",
			Printer: "printer",
			PurchaseOrder: "order",
			PurchaseOrderRow: "order_item",
			Rack: "rack",
			RequestFulfillment: "process",
			ReqFulfilWOTmpl: "process",
			Rete: "network",
			RFIT110002: "process",
			RFIT100003: "process",
			RisorsaIT: "asset",
			Role: "employee",
			Sede: "headquarters",
			Server: "server",
			ServiceCategory: "process",
			ServiceRequest: "process",
			SMIT120001: "process",
			Software: "software",
			SWCatalogue: "softwareCatalogue",
			InfrastructureSW: "softwareCatalogue",
			Storage: "disk",
			Supplier: "supplier",
			TechnicalServices: "process",
			Terminale: "terminal",
			VirtualIP: "IP",
			//------------------
			CentroDiCosto: "money",
			Locazione: "location",
			Building: "location",
			Notebook: "laptop",
			SMIT120001: "process",
			Assegnazione: "assignement",
			Contratto: "contract",
			Installazioni: "installation",
			Fornitore: "supplier",
			ModelloTerminale: "brand",
			ModelloComputer: "brand",
			DiscoLogico: "logicdisk",
			FiltroSCCM: "centos_linux",
			Osriga: "SAP",
			VMServer: "virtualserver",
			Database: "virtualdisk",
			GenericClientSW: "software",
			AnagPool: "virtualdisk",
			Indirizzo: "IP",
			Esterno: "employee2",
			GUICOMPOUND: "compound",
			Client: "client",
			Monitor: "monitor",
			OU: "accesses",
			PhysicalServer: "server",
			relation: "relation"
		},
		key2Sprite: {
			accesses: "devices/blockdevice-2.png",
			application: "categories/applications-other-4.png",
			asset: "devices/computer-6.png",
			assignement: "mimetypes/text-x-script.png",
			brand: "others/shield-2.png",
			client: "devices/computer-4.png",
			company: "buildings/coal-power-plant-icon.png",
			compound: "categories/applications-office-2.png",
			contract: "mimetypes/text-x-changelog.png",
			disk: "devices/drive-harddisk-3.png",
			employee: "buildings/Office-Customer-Male-Light-icon.png",
			employee2: "buildings/Office-Customer-Male-Light-icon.png",
			headquarters: "buildings/school-icon.png",
			installation: "categories/system-settings-2.png",
			laptop: "devices/computer-laptop.png",
			location: "buildings/home-icon.png",
			mobile: "devices/pda_alt.png",
			money: "buildings/Money-icon.png",
			monitor: "devices/video-display.png",
			networkbox: "devices/network-hub.png",
			networkinterface: "devices/network-wireless-4.png",
			
			operationalareas: "buildings/city-icon.png",
			order: "categories/applications-office-6.png",
			order_item: "mimetypes/text-x-preview.png",
			printer: "devices/printer-4.png",
			process: "actions/system-run-2-green.png",
			rack: "devices/computer-server-rack_mount.png",
			relation: "actions/view-refresh-2.png",
			selectionShape: "buildings/select.png",
			server: "places/gnome-style/network-server.png",
			softwareCatalogue: "apps/system-software-installer-3.png",
			supplier: "others/people-delivery.png",
			terminal: "devices/computer-3.png",
			virtualdisk: "places/crystal-style/database.png",
			//-------------------------
			disk: "devices/media-floppy-3.5-2.png",
			logicdisk: "places/oxygen-style/server-database.png",
			centos_linux: "apps/distributions-centos_linux.png",
			SAP: "buildings/sap.png",
			virtualserver: "devices/media-floppy-3.5-2.png",
			network: "places/crystal-style/network.png",
			software: "apps/system-software-install.png",
			IP: "places/crystal-style/socket.png",
		},
		class2Sprite: function(className) {
			var sprite = $.Cmdbuild.appConfigUrl + "sprites/";
			if (this.class2Key[className] && this.key2Sprite[this.class2Key[className]]) {
				sprite += this.key2Sprite[this.class2Key[className]];
			} else {
				sprite += "others/circle_blue.png";
			}
			return sprite;
		}
	};
	$.Cmdbuild.SpriteArchive = SpriteArchive;
})(jQuery);