(function($) {
	var SpriteArchive = {
		class2Key: {
			selectionShape: "selectionShape",
			Dipendente: "employee",
			InternalEmployee: "employee",
			BusinessServices: "process",
			BusinessService: "process",
			TechnicalServices: "process",
			BusinessProcess: "process",
			RequestFulfillment: "process",
			ServiceRequest: "process",
			ServiceCategory: "process",
			SMIT120001: "process",
			ImacTrans: "process",
			DepMgt: "process",
			RFIT110002: "process",
			RFIT100003: "process",
			GestioneModifiche: "process",
			Sede: "headquarters",
			Azienda: "company",
			OperationalAreas: "operationalareas",
			CentroDiCosto: "money",
			Locazione: "location",
			Building: "location",
			RisorsaIT: "asset",
			Server: "server",
			Terminale: "terminal",
			Notebook: "laptop",
			Desktop: "terminal",
			SMIT120001: "process",
			Assegnazione: "assignement",
			Contratto: "contract",
			Installazioni: "installation",
			Fornitore: "supplier",
			Supplier: "supplier",
			ModelloTerminale: "brand",
			ModelloComputer: "brand",
			DiscoLogico: "logicdisk",
			FiltroSCCM: "centos_linux",
			Osriga: "SAP",
			VMServer: "virtualserver",
			Database: "virtualdisk",
			Rete: "network",
			Software: "software",
			GenericClientSW: "software",
			AnagPool: "virtualdisk",
			Indirizzo: "IP",
			Esterno: "employee2",
			GUICOMPOUND: "compound",
			Client: "client",
			Printer: "printer",
			OU: "accesses",
			PhysicalServer: "server",
			relation: "relation"
		},
		key2Sprite: {
			selectionShape: "buildings/select.png",
			process: "actions/system-run-2-green.png",
			employee: "buildings/Office-Customer-Male-Light-icon.png",
			employee2: "buildings/Office-Customer-Male-Light-icon.png",
			location: "buildings/home-icon.png",
			company: "buildings/coal-power-plant-icon.png",
			headquarters: "buildings/school-icon.png",
			money: "buildings/Money-icon.png",
			operationalareas: "buildings/city-icon.png",
			asset: "devices/computer-6.png",
			server: "devices/computer-server-rack_mount.png",
			terminal: "devices/computer-3.png",
			assignement: "mimetypes/text-x-script.png",
			contract: "mimetypes/text-x-changelog.png",
			supplier: "others/people-delivery.png",
			brand: "others/shield-2.png",
			installation: "categories/system-settings-2.png",
			disk: "devices/media-floppy-3.5-2.png",
			logicdisk: "places/oxygen-style/server-database.png",
			centos_linux: "apps/distributions-centos_linux.png",
			SAP: "buildings/sap.png",
			virtualserver: "devices/media-floppy-3.5-2.png",
			network: "places/crystal-style/network.png",
			software: "apps/system-software-install.png",
			virtualdisk: "places/crystal-style/database.png",
			IP: "places/crystal-style/socket.png",
			compound: "categories/applications-office-2.png",
			client: "devices/computer-4.png",
			printer: "devices/printer-4.png",
			laptop: "devices/computer-laptop.png",
			accesses: "devices/blockdevice-2.png",
			disk: "devices/drive-harddisk-3.png",
			relation: "actions/view-refresh-2.png"
		},
		class2Sprite: function(className) {
			var sprite = $.Cmdbuild.appConfigUrl + "sprites/";
			if (this.class2Key[className] && this.key2Sprite[this.class2Key[className]]) {
				sprite += this.key2Sprite[this.class2Key[className]];
			} else {
				sprite += "others/circle_blue.png";
			}
			return sprite;
		}
	};
	$.Cmdbuild.SpriteArchive = SpriteArchive;
})(jQuery);