<script type="text/javascript" src="javascripts/cmdbuild/administration/class/AttributeForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/AttributeSortingGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/AttributeGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/ClassForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/DomainGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/GeoAttributeForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/GeoAttributePanel.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/GeoServerForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/GeoServerLayersGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/MetadataWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/ModClass.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/SetOrderWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/form/CMFormTemplate.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/domain/CMDomainAccordion.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/domain/CMDomainForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/domain/CMDomainFormController.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/domain/CMDomainAttributes.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/domain/ModDomain.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/domain/ModDomainController.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/gis/LayerGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/class/LayerVisibilityGrid.js"></script><!-- inherit from FeatureTypeGrid -->
<script type="text/javascript" src="javascripts/cmdbuild/administration/gis/LayerController.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/gis/ModExternalServices.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/gis/ModGeoServer.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/gis/ModGis.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/gis/ModIcons.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/gis/ModLayerOrder.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/lookup/LookupForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/lookup/LookupGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/lookup/LookupTypeForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/lookup/ModLookup.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/menu/MenuPanel.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/menu/ModMenu.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/report/ImportJRFormStep1.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/report/ImportJRFormStep2.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/report/ReportForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/report/ModReport.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/report/ReportGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/security/GroupForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/security/UserPerGroup.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/security/ModSecurity.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/security/ModUser.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/security/PrivilegeGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/security/UserForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/security/UserGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/scheduler/SchedulerUI.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/scheduler/JobGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/scheduler/JobPanel.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/scheduler/JobParameterGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/scheduler/CronEditWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/ModWorkflow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/XPDLDownloadForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/workflow/XPDLUploadForm.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/TemplateModSetup.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/ModSetupGenericOption.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/ModSetupGraph.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/ModSetupLegacydms.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/ModSetupEmail.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/ModSetupServer.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/ModSetupWorkflow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/ModSetupGis.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration/setup/SetupTree.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/administration.js"></script>