<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/BaseAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/SimpleQueryAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/RangeQueryAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/TextualQueryAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/DecimalAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/DoubleAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/IntegerAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/IPAddressAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/DateAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/TimeStampAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/TimeAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/BooleanAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/ComboAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/LookupAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/ReferenceAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/ForeignKeyAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/StringAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/CharAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/widgetBuilders/TextAttribute.js"></script>
	
<script type="text/javascript" src="javascripts/cmdbuild/management/FixedCardGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/template/TemplateResolver.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/attachment/AddAttachmentWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/attachment/EditAttachmentWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/AddCardWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/CardExtensionProvider.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/CardListGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/CardTabPanel.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/CardWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/filter/Attachments.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/filter/Attributes.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/filter/relations/DomainCardListFilter.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/filter/relations/DomainCardList.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/filter/relations/FilterRelationsDomainGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/filter/Relations.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/filter/SaveFilter.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/graph/GraphWindow.js"></script>

<script type="text/javascript" src="javascripts/cmdbuild/management/card/masterDetail/AddDetailActionMenu.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/masterDetail/DetailAttachmentsWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/masterDetail/DetailNoteWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/masterDetail/DetailWindow.js"></script>	
<script type="text/javascript" src="javascripts/cmdbuild/management/card/masterDetail/AddDetailWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/masterDetail/EditDetailWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/masterDetail/MasterDetailCardGrid.js"></script>

<script type="text/javascript" src="javascripts/cmdbuild/management/card/CardListWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/relation/DomainCardListWindow.js"></script>

<script type="text/javascript" src="javascripts/cmdbuild/management/card/ModCard.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/relation/AddRelationWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/relation/DomainStore.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/relation/EditRelationWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/SearchFilterWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/CardAttachmentsTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/CardHistoryTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/CardMapTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/CardMasterDetailTab.js"></script>

<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/CardNotesTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/CardRelationsTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/EditablePanel.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/cardTab/CardTabController.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/card/tabs/cardTab/CardTabUI.js"></script>

<script type="text/javascript" src="javascripts/cmdbuild/management/field/BooleanDisplayField.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/field/EntityRemoverDisplayField.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/field/FieldManager.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/field/LookupField.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/field/GridSearchField.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/field/SearchableCombo.js"></script>	
<script type="text/javascript" src="javascripts/cmdbuild/management/field/ReferenceField.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/field/ForeignKeyField.js"></script>

<script type="text/javascript" src="javascripts/cmdbuild/management/menu/MenuTree.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/ReferenceSearchWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/report/ModReport.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/report/ReportGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/report/ReportParamWin.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/utilities/BulkCardAttributesPanel.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/utilities/ModBulkCardUpdate.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/utilities/ModChangePassword.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/utilities/UtilitiesTree.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/utilities/importcsv/CSVGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/utilities/ModExportCSV.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/utilities/importcsv/ModImportCSV.js"></script>	
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/ActivityTabPanel.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/BaseExtendedAttribute.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/CreateModifyCard.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/LinkCards.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/manageRelation/ManageRelation.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/manageRelation/ManageRelationTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/email/EmailWindow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/email/EmailGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/email/ManageEmail.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/OpenNote.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/OpenAttachment.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/extendedattribute/CreateReport.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/ModWorkflow.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/WorkflowCardListGrid.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/tabs/ActivityOptionTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/tabs/ActivityTab.js"></script>
<script type="text/javascript" src="javascripts/cmdbuild/management/workflow/tabs/ActivityNotesTab.js"></script>

<script type="text/javascript" src="javascripts/cmdbuild/management.js"></script>