(function() {

	/**
	 * Constants with the standard parameter names
	 */
	Ext.define('CMDBuild.ServiceProxy.parameter', {
		statics: {
			ACTIVE: 'active',
			ADDRESS: 'address',
			ALFRESCO_LOOKUP_TYPE: 'alfrescoLookupType',
			ATTRIBUTES: 'attributes',
			BCC: 'bcc',
			BODY: 'body',
			CARDS: 'cards',
			CARD_ID: 'cardId',
			CC: 'cc',
			CLASS_ID: 'classId',
			CLASS_NAME: 'className',
			CONFIRMED: 'confirmed',
			DATASOURCE: 'dataSourceName',
			DESCRIPTION: 'description',
			DISPLAY_IN_GRID: 'isbasedsp',
			DOMAIN_ID: 'domainId',
			DOMAIN_LIMIT: 'domainlimit',
			DOMAIN_NAME: 'domainName',
			DOMAIN_SOURCE: 'src',
			EDITOR_TYPE: 'editorType',
			EMAIL_ACCOUNT: 'emailAccount',
			EMAIL_TEMPLATE: 'emailTemplate',
			ENABLE_MOVE_REJECTED_NOT_MATCHING: 'enableMoveRejectedNotMatching',
			ENTRY_TYPE: 'entryType',
			FIELD_MODE: 'fieldmode',
			FILTER: 'filter',
			FILTER_FROM_ADDRESS: 'fromAddressFilter',
			FILTER_SUBJECT: 'subjectFilter',
			FK_DESTINATION: 'fkDestination',
			FORMAT: 'format',
			FROM: 'from',
			GROUP: 'group',
			GROUP_ID: 'groupId',
			GROUP_NAME: 'groupName',
			ID: 'id',
			IMAP_PORT: 'imapPort',
			IMAP_SERVER: 'imapServer',
			IMAP_SSL: 'imapSsl',
			INCOMING_FOLDER: 'incomingFolder',
			INDEX: 'index',
			IS_DEFAULT: 'isDefault',
			KEY_END: 'keyEnd',
			KEY_INIT: 'keyInit',
			LENGTH: 'len',
			LOOKUP: 'lookup',
			MENU: 'menu',
			NAME: 'name',
			NOT_NULL: 'isnotnull',
			PASSWORD: 'password',
			POLLING_FREQUENCY: 'pollingFrequency',
			PRECISION: 'precision',
			PRIVILEGED_OBJ_DESCRIPTION: 'privilegedObjectDescription',
			PRIVILEGED_OBJ_ID: 'privilegedObjectId',
			PROCESSED_FOLDER: 'processedFolder',
			REJECTED_FOLDER: 'rejectedFolder',
			RELATION_ID: 'relationId',
			RELATION_MASTER_SIDE: 'master',
			RETRY_WITHOUT_FILTER: 'retryWithoutFilter',
			SCALE: 'scale',
			SMTP_PORT: 'smtpPort',
			SMTP_SERVER: 'smtpServer',
			SMTP_SSL: 'smtpSsl',
			SORT: 'sort',
			SOURCE_CLASS_NAME: 'sourceClassName',
			SOURCE_FUNCTION: 'sourceFunction',
			STATUS: 'status',
			SUBJECT: 'subject',
			TABLE_TYPE: 'tableType',
			TO: 'to',
			TYPE: 'type',
			UNIQUE: 'isunique',
			USERNAME: 'username',
			VALUE_END: 'valueEnd',
			VALUE_INIT: 'valueInit',
			WIDGET: 'widget',
			WIDGET_ID: 'widgetId',
			WORKFLOW: 'workflow'
		}
	});

})();